name: 🔥 Deploy to Firebase App Distribution

on:
  push:
    branches:
      - release # Only in release branch

jobs:
  deploy:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"
          cache: "gradle"
      - name: Generate Keystore
        env:
          KEYSTORE_B64: ${{ secrets.APP_KEYSTORE }}
        run: |
          echo $KEYSTORE_B64 \
          | sed 's/[^A-Za-z0-9+/=]//g' \
          | base64 -d > keystore.jks
        working-directory: ./android/app

      - name: Build Release APK
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease
        working-directory: ./android

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION }}
          groups: tester
          releaseNotesFile: android/release_notes.txt
          file: android/app/build/outputs/bundle/release/app-release.aab
